
v1<-readline("enter the first number")
v1<-as.integer(v1)
v2<-readline("enter the second number")
v2<-as.integer(v2)
print(v1)
print(v2)
print("options are")
print("addition")
print("sub")
print("div")
print("mul")
option<-readline("enter your option")
option<-as.integer(option)
value<-switch(option,(v1+v2),(v1-v2),(v1/v2),(v1*v2))
print(value)